name: Prettier Check

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npx prettier --check .
